"""initial schema

Revision ID: 06356270b436
Revises: 
Create Date: 2026-09-13 23:04:35.936751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06356270b436'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('course', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('prep_minutes', sa.Integer(), nullable=True),
    sa.Column('chunk_minutes', sa.Integer(), nullable=True),
    sa.Column('weight_value', sa.Float(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=True),
    sa.Column('recurrence_raw', sa.String(length=255), nullable=True),
    sa.Column('recurrence_kind', sa.String(length=16), nullable=True),
    sa.Column('recurrence_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recurrence_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('raw_input', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("item_type IN ('assignment', 'habit', 'event')", name='ck_items_type'),
    sa.CheckConstraint("source_type IN ('manual', 'moodle', 'imported', 'system')", name='ck_items_source'),
    sa.CheckConstraint("status IN ('planned', 'active', 'done', 'cancelled', 'archived')", name='ck_items_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_course'), ['course'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_items_user_type', ['user_id', 'item_type'], unique=False)

    op.create_table('user_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('matrix_homeserver', sa.String(length=255), nullable=True),
    sa.Column('matrix_user_id', sa.String(length=255), nullable=True),
    sa.Column('matrix_room_id', sa.String(length=255), nullable=True),
    sa.Column('matrix_access_token', sa.Text(), nullable=True),
    sa.Column('digest_enabled', sa.Boolean(), nullable=False),
    sa.Column('moodle_ics_url', sa.Text(), nullable=True),
    sa.Column('moodle_import_enabled', sa.Boolean(), nullable=False),
    sa.Column('moodle_last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('apple_feed_token', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('user_integrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_integrations_apple_feed_token'), ['apple_feed_token'], unique=True)

    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('default_due_time', sa.String(length=5), nullable=False),
    sa.Column('default_digest_time', sa.String(length=5), nullable=False),
    sa.Column('default_assignment_prep_minutes', sa.Integer(), nullable=True),
    sa.Column('default_chunk_minutes', sa.Integer(), nullable=True),
    sa.Column('workday_start_time', sa.String(length=5), nullable=True),
    sa.Column('workday_end_time', sa.String(length=5), nullable=True),
    sa.Column('upcoming_lookahead_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('item_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'tag', name='uq_item_tag')
    )
    with op.batch_alter_table('item_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_item_tags_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_item_tags_tag'), ['tag'], unique=False)

    op.create_table('occurrences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('occurrence_date', sa.Date(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prep_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('remaining_minutes', sa.Integer(), nullable=True),
    sa.Column('recommended_minutes', sa.Integer(), nullable=True),
    sa.Column('completion_percent', sa.Integer(), nullable=False),
    sa.Column('is_generated', sa.Boolean(), nullable=False),
    sa.Column('generator_key', sa.String(length=128), nullable=True),
    sa.Column('manual_override', sa.Boolean(), nullable=False),
    sa.Column('source_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('planned', 'active', 'done', 'cancelled', 'skipped')", name='ck_occ_status'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'generator_key', name='uq_occ_generator'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('occurrences', schema=None) as batch_op:
        batch_op.create_index('ix_occ_user_date', ['user_id', 'occurrence_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_occurrences_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_occurrences_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_occurrences_occurrence_date'), ['occurrence_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_occurrences_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_occurrences_user_id'), ['user_id'], unique=False)

    op.create_table('work_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurrence_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('minutes_spent', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['occurrence_id'], ['occurrences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_logs_occurrence_id'), ['occurrence_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_logs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_work_logs_occurrence_id'))

    op.drop_table('work_logs')
    with op.batch_alter_table('occurrences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_occurrences_user_id'))
        batch_op.drop_index(batch_op.f('ix_occurrences_status'))
        batch_op.drop_index(batch_op.f('ix_occurrences_occurrence_date'))
        batch_op.drop_index(batch_op.f('ix_occurrences_item_id'))
        batch_op.drop_index(batch_op.f('ix_occurrences_due_at'))
        batch_op.drop_index('ix_occ_user_date')

    op.drop_table('occurrences')
    with op.batch_alter_table('item_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_item_tags_tag'))
        batch_op.drop_index(batch_op.f('ix_item_tags_item_id'))

    op.drop_table('item_tags')
    op.drop_table('user_settings')
    with op.batch_alter_table('user_integrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_integrations_apple_feed_token'))

    op.drop_table('user_integrations')
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index('ix_items_user_type')
        batch_op.drop_index(batch_op.f('ix_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_items_course'))

    op.drop_table('items')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
